steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agent-factory-ui:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agent-factory-ui:latest'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agent-factory-ui:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agent-factory-ui:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agent-factory-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agent-factory-ui:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'VITE_API_URL=https://your-api-url'

images:
  - 'gcr.io/$PROJECT_ID/agent-factory-ui:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/agent-factory-ui:latest'

options:
  logging: CLOUD_LOGGING_ONLY
